# Generated by Django 3.1.4 on 2020-12-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20201216_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
