# Generated by Django 3.1.4 on 2021-01-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0006_auto_20210105_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
